"""Structured chart definitions for summary-section documentation."""

# Each chart: title, badge, badge_class, measures, read, use, action (optional)


def _c(title, badge, badge_class, measures, read, use, action=""):
    return {
        "title": title,
        "badge": badge,
        "badge_class": badge_class,
        "measures": measures,
        "read": read,
        "use": use,
        "action": action,
    }


CHART_SPECS = {
    "hrms_dashboard_my": [
        _c("Attendance (month)", "Calendar + bar", "badge-bar",
           "Present / absent days and attendance rate for the current month",
           "Calendar strip colours each day; bar shows monthly attendance percentage",
           "Scan for unexpected absence clusters before month-end",
           "Open Attendance to mark or correct days"),
        _c("Hours over 6 weeks", "Stacked bar", "badge-bar",
           "Billable, non-billable, and leave hours per week",
           "Stacked segments show composition; total bar height = weekly hours",
           "Track whether billable ratio is stable or drifting",
           "Open Timesheet for the week that looks off"),
        _c("This week at a glance", "Donut", "badge-donut",
           "Utilization breakdown — billable vs other hours this week",
           "Largest slice = dominant time type; centre may show total hours",
           "Compare against org target (~80%+ billable if policy requires)",
           "Add billable entries on Timesheet if ratio is low"),
        _c("Task queue mix", "Donut", "badge-donut",
           "Open tasks grouped by workflow status",
           "Each slice = share of tasks in that column/status",
           "Spot blocked or overdue concentration",
           "Open Task Board or My Tasks to clear blockers"),
        _c("Leave & holidays", "List", "badge-line",
           "Leave hours booked plus upcoming public holidays",
           "List rows show dates and types; not a chart but part of summary strip",
           "Plan around team and personal availability",
           "Book leave on Timesheet or HR portal as per policy"),
    ],
    "hrms_dashboard_team": [
        _c("Headcount trend", "Line", "badge-line",
           "Active employee count over the last 6 months",
           "Upward slope = growth; dips may indicate exits or scope change",
           "Monthly workforce planning checkpoint",
           "Cross-check with Employees directory after sharp changes"),
        _c("Joins & exits", "Stacked area", "badge-area",
           "Monthly join vs exit events",
           "Overlapping areas show churn vs hiring in the same month",
           "Identify retention issues or hiring spikes",
           "Drill into Employees list filtered by join date"),
        _c("Gender mix", "Donut", "badge-donut",
           "Gender distribution across scoped roster",
           "Slice size = proportion of each category",
           "DEI reporting and roster balance review",
           "Export roster if external reporting is required"),
        _c("Employment type", "Donut", "badge-donut",
           "Permanent, contract, intern, and other types",
           "Shows workforce composition by contract type",
           "Contract-heavy teams may need renewal tracking",
           "Filter Employees register by employment type"),
        _c("Tenure bands", "Column bar", "badge-bar",
           "Headcount in 0–1y, 1–3y, 3–5y, 5y+ buckets",
           "Taller columns = more employees in that tenure band",
           "Succession and experience mix analysis",
           "Pair with skills chart for capability planning"),
        _c("Work locations", "Column bar", "badge-bar",
           "Office, remote, and region counts",
           "Compare site vs remote distribution",
           "Facilities and timezone planning",
           "Update employee profiles if locations are stale"),
        _c("Top skills", "Horizontal bar", "badge-bar",
           "Most tagged skills in the scoped roster",
           "Longest bars = most common skill tags",
           "Capability demand and bench strength",
           "Open employee profiles to verify skill tags"),
        _c("Departments & teams", "Horizontal bar", "badge-bar",
           "Headcount by org grouping",
           "Shows load distribution across teams",
           "Rebalance hiring or transfers if one bar dominates",
           "Use team scope bar to narrow before comparing"),
        _c("Grade & band", "Treemap", "badge-treemap",
           "Compensation band distribution",
           "Tile area = count in each band",
           "Compensation structure review (permission required)",
           "HR-only — do not share outside authorized roles"),
    ],
    "hrms_employees": [
        _c("Grade & band", "Treemap", "badge-treemap", "Compensation band distribution", "Tile size = headcount per band", "Compensation planning", "HR review only"),
        _c("Headcount trend", "Line", "badge-line", "Active employees over 6 months", "Trend line shows roster growth or shrinkage", "Workforce planning", "Compare with Team dashboard"),
        _c("Joins & exits", "Stacked area", "badge-area", "Monthly join vs exit events", "Green/red areas show hiring vs attrition", "Churn analysis", "Investigate exit spikes"),
        _c("Gender mix", "Donut", "badge-donut", "Gender distribution", "Slice = share of roster", "DEI metrics", "Filter register after review"),
        _c("Employment type", "Donut", "badge-donut", "Permanent, contract, intern, etc.", "Contract vs permanent split", "Resource planning", "Align with project staffing"),
        _c("Tenure bands", "Column", "badge-bar", "0–1y, 1–3y, 3–5y, 5y+ buckets", "Column height = count in band", "Experience mix", "Succession planning"),
        _c("Work locations", "Column", "badge-bar", "Office / remote / region counts", "Location distribution", "Hybrid workforce planning", "Update stale profiles"),
        _c("Top skills", "H-bar", "badge-bar", "Most tagged skills in roster", "Longest bar = most common skill", "Capability map", "Tag skills on profiles"),
        _c("Departments & teams", "H-bar", "badge-bar", "Org grouping headcount", "Team size comparison", "Load balancing", "Use team filter on register"),
    ],
    "sales_bid": [
        _c("Bid intake trend", "Area", "badge-area", "New bids per month, 6 months", "Rising area = heavier sales intake", "Velocity tracking", "Staff bid desk if trend spikes"),
        _c("Win / loss snapshot", "Column", "badge-bar", "Won, lost, still open counts", "Compare column heights for win rate", "Pipeline outcome review", "Follow up open bids"),
        _c("Portfolio outcomes", "Donut", "badge-donut", "Open / won / lost / other closed", "Historical vs active balance", "Portfolio health", "Close stale open bids"),
        _c("Pipeline age", "Donut", "badge-donut", "Fresh / active / stale open bids", "Stale slice needs attention", "Aging pipeline cleanup", "Contact owners on stale bids"),
        _c("By status", "Donut", "badge-donut", "Active bid status mix", "Operational workload distribution", "Desk prioritization", "Filter list by status"),
        _c("Stage volume", "H-bar", "badge-bar", "Count per funnel stage", "Longest bar = bottleneck stage", "Process improvement", "Review stage SLAs"),
        _c("Geography mix", "H-bar wide", "badge-bar", "Countries represented", "Regional demand signal", "Territory planning", "Align with regional reps"),
        _c("Kind of study", "H-bar", "badge-bar", "Research study types", "Service line demand", "Capability investment", "Match to delivery teams"),
        _c("Bid type", "V-bar", "badge-bar", "Commercial vs study categories", "Revenue type mix", "Forecasting", "Filter bid list by type"),
        _c("CRM linkage", "Donut", "badge-donut", "Salesforce linked vs manual", "Integration completeness", "Data quality", "Link orphan bids to CRM"),
        _c("Owner workload", "H-bar wide", "badge-bar", "Bids per owner", "Balance assignments", "Rep capacity", "Reassign overloaded owners"),
        _c("Study disciplines", "H-bar", "badge-bar", "Tagged disciplines", "Capability demand", "Hiring/training signals", "Tag disciplines on new bids"),
    ],
    "sales_po": [
        _c("Delivery funnel", "Diagram", "badge-funnel", "Stage progression horizontal", "Width = volume at each stage", "Contract pipeline shape", "Unblock stuck stages"),
        _c("By status", "Donut", "badge-donut", "Active contract statuses", "Live workload mix", "Operations review", "Filter PO list"),
        _c("Portfolio mix", "Donut", "badge-donut", "Pipeline / completed / closed / archived", "Active vs historical balance", "Portfolio reporting", "Archive completed contracts"),
        _c("Delivery health", "Donut", "badge-donut", "Timeline risk on open contracts", "Overdue vs on-track split", "Risk escalation", "Open overdue PO details"),
        _c("Creation trend", "Area smooth", "badge-area", "New contracts, 6 months", "Intake rate over time", "Sales-to-delivery handoff", "Plan delivery capacity"),
        _c("Project types", "V-bar distributed", "badge-bar", "Contract delivery types", "Service mix under contract", "Resource alignment", "Match teams to types"),
        _c("Creation channel", "Donut", "badge-donut", "Salesforce vs manual", "Integration adoption", "Data governance", "Prefer CRM-created POs"),
        _c("Bid linkage", "Donut", "badge-donut", "Bid-linked vs standalone", "Sales traceability", "Revenue attribution", "Link standalone POs to bids"),
        _c("Funnel volume", "H-bar", "badge-bar", "Per-stage counts", "Bottleneck identification", "Stage SLA review", "Escalate stuck volume"),
        _c("Top accounts", "H-bar", "badge-bar", "Top accounts by contract count", "Client concentration", "Account management", "Diversify if one bar dominates"),
        _c("By team", "H-bar", "badge-bar", "Contracts per delivery team", "Team load from sales", "Capacity planning", "Rebalance assignments"),
    ],
    "project_list": [
        _c("By status", "Donut", "badge-donut", "Active status mix", "Centre may show active count", "Portfolio skew check", "Filter list by status"),
        _c("Portfolio mix", "Donut", "badge-donut", "Open / completed / closed", "Live vs historical balance", "Reporting scope", "Toggle SHOW preset"),
        _c("Timeline health", "Donut", "badge-donut", "Overdue / due soon / on track / no date", "Risk concentration", "Scheduling interventions", "Open overdue projects"),
        _c("Creation trend", "Area", "badge-area", "New projects, 6 months", "Intake spikes or quiet periods", "Capacity forecasting", "Plan hiring if trend rises"),
        _c("Project types", "H-bar", "badge-bar", "Delivery model mix", "Service line distribution", "Strategic focus", "Align sales pipeline"),
        _c("Billing mix", "Donut", "badge-donut", "Billable type split", "Finance alignment", "Revenue recognition", "Review non-billable share"),
        _c("PO linkage", "Donut", "badge-donut", "PO-linked vs standalone", "Contract coverage", "Sales follow-up", "Link orphan projects"),
        _c("Completed share", "Donut %", "badge-donut", "Completed vs in delivery", "Throughput ratio", "Delivery performance", "Celebrate + learn from delays"),
        _c("Open pipeline load", "Donut %", "badge-donut", "New / assigned / in progress", "Funnel concentration", "WIP management", "Limit new starts if overloaded"),
        _c("Automation", "Donut", "badge-donut", "Automation enabled vs disabled", "Workflow adoption", "Efficiency drive", "Enable automation on eligible projects"),
        _c("Top accounts", "H-bar", "badge-bar", "Top 8 accounts by project count", "Client concentration risk", "Account strategy", "Diversify portfolio"),
        _c("By team", "H-bar", "badge-bar", "Top 8 teams by project count", "Load distribution", "Team balancing", "Reassign if uneven"),
        _c("Priority", "V-bar", "badge-bar", "Urgent / high / medium / low", "Escalation volume", "War-room focus", "Triage urgent projects first"),
        _c("Shared visibility", "Donut", "badge-donut", "Shared vs private projects", "Collaboration vs restricted", "Security review", "Adjust sharing settings"),
        _c("Complexity", "V-bar", "badge-bar", "Basic / medium / complex", "Resourcing needs", "Staff senior leads on complex", "Right-size teams"),
        _c("Capex / Opex", "Donut", "badge-donut", "Capital vs operating", "Financial classification", "Finance reporting", "Tag projects correctly"),
        _c("Hours estimated", "Donut", "badge-donut", "With hours vs missing estimates", "Planning completeness", "Estimate hygiene", "Click gap list to add estimates"),
    ],
    "taskboard": [
        _c("Delivery funnel", "Funnel", "badge-funnel", "Task count per kanban column", "Wide top = backlog; narrow bottom = done", "Flow efficiency", "Limit WIP in middle columns"),
        _c("Workflow mix", "Donut", "badge-donut", "Share of tasks in each column", "Column dominance", "Bottleneck detection", "Move blocked tasks first"),
        _c("Billable scope", "Donut", "badge-donut", "Project vs non-project vs other", "Billable alignment", "Utilization impact", "Link tasks to projects"),
        _c("Flow snapshot", "Distributed bar", "badge-bar", "Column counts side-by-side", "Compare column volumes", "Daily stand-up metric", "Rebalance assignees"),
        _c("Top categories", "V-bar", "badge-bar", "Most frequent task categories", "Work type mix", "Process design", "Standardize high-volume categories"),
    ],
    "task_activity": [
        _c("Status mix", "Donut", "badge-donut", "Completed, in progress, assigned, etc.", "Progress distribution", "Sprint health", "Clear in-progress items"),
        _c("Priority breakdown", "Bar", "badge-bar", "Urgent through low", "Escalation load", "Daily triage", "Address urgent bar first"),
        _c("Checklist progress", "Donut", "badge-donut", "Done vs open checklist items", "Sub-task completion", "Quality gate", "Close open checklist items"),
        _c("Activity type", "Bar", "badge-bar", "Work item type distribution", "Work mix", "Process analytics", "Filter activity list"),
        _c("Outcome", "Donut", "badge-donut", "Success / partial / blocked outcomes", "Delivery quality", "Retro input", "Investigate blocked outcomes"),
    ],
    "project_dashboard_my": [
        _c("Workload trend", "Line", "badge-line", "Your assigned project hours over selected period", "Slope shows rising or falling load", "Personal capacity check", "Decline new assignments if overloaded"),
        _c("Performance radar", "Radar", "badge-bar", "Multi-axis delivery score across active projects", "Spikes show strengths; dips show risk areas", "Self-assessment before reviews", "Focus on lowest radar axis"),
        _c("Status donuts", "Donut", "badge-donut", "Your projects by delivery status", "Slice = share per status", "See if work is stuck in one state", "Open at-risk projects first"),
        _c("Estimate variance bars", "Bar", "badge-bar", "Planned vs logged hours variance per project", "Bar above zero = over run; below = under", "Estimate accuracy", "Update estimates on overrun projects"),
        _c("Portfolio treemap", "Treemap", "badge-treemap", "Your projects sized by effort or value", "Tile area = relative weight", "Where time concentrates", "Rebalance if one tile dominates"),
        _c("Estimate vs completion bubble", "Bubble", "badge-bar", "Completion % vs estimate size", "Top-right bubbles = large and nearly done", "Close-out prioritization", "Finish nearly-complete projects"),
    ],
    "project_dashboard_manager": [
        _c("Portfolio KPI cards", "KPI tiles", "badge-line", "Active, overdue, at-risk, completed counts", "Clickable tiles may pre-filter Project List", "Executive snapshot", "Click KPI to drill into list"),
        _c("Risk scatter", "Scatter", "badge-bar", "Projects plotted by risk vs impact", "Top-right dots = high priority risks", "Escalation triage", "Open flagged projects"),
        _c("Throughput views", "Bar", "badge-bar", "Completed deliverables or tasks over period", "Bar height = throughput volume", "Delivery velocity", "Investigate throughput drops"),
        _c("Velocity lines", "Line", "badge-line", "Trend of completion rate over time", "Upward = accelerating delivery", "Sprint/portfolio planning", "Adjust WIP if velocity falls"),
        _c("Deadline heatmap", "Heatmap", "badge-treemap", "Due dates density by week/day", "Hot cells = deadline clusters", "Schedule conflict detection", "Spread deadlines or add resources"),
    ],
    "mobile_insights_time": [
        _c("Utilisation & billable target", "Dual gauge", "badge-donut",
           "Billable ÷ total hours; billable vs 40h target",
           "Needle/gauge shows % utilisation and target gap",
           "Weekly self-check on billable ratio", "Record more billable time if below target"),
        _c("Hours mix", "Donut", "badge-donut",
           "Billable / non-billable / leave slices",
           "Slice size = hour type share", "Understand time composition", "Adjust daily logging"),
        _c("Daily stacked hours", "Stacked bar", "badge-bar",
           "Per weekday: billable → non-billable → leave",
           "Stack height = total hours that day", "Spot weak billable days", "Backfill timesheet entries"),
        _c("Billable by project", "Horizontal bar", "badge-bar",
           "Top projects by billable hours",
           "Longest bar = highest billable project", "Project focus review", "Open project hub for top bar"),
        _c("Time by account", "Horizontal bar", "badge-bar",
           "Hours grouped by account", "Client time concentration", "Account management", "Verify account mapping"),
        _c("Billable trend", "Line + area", "badge-line",
           "Billable hours per weekday",
           "Line shows daily billable trend", "Momentum tracking", "Improve declining days"),
    ],
}

# Reports are catalog entries, not charts — handled as feature cards separately
REPORT_ITEMS = [
    ("Data Dump", "Raw export of operational records for the date/team scope", "Analysts, integrations"),
    ("Employee Utilization", "Billable vs available hours by employee", "Resource managers"),
    ("My Utilization", "Personal utilization summary", "Individual contributors"),
    ("My Timesheet Data", "Your logged hours detail", "Individual contributors"),
    ("15% Report", "Compliance/reporting template (org-specific)", "Finance, compliance"),
    ("Est vs Actual (Deliverables)", "Planned vs logged effort at deliverable level", "Project managers"),
    ("Est vs Actual (Activities)", "Planned vs logged at work item / activity level", "Delivery leads"),
    ("Site Activity", "Activity at site/location granularity", "Field operations"),
    ("Weekwise Utilization", "Utilization broken down by week", "Capacity planning"),
    ("Weekly PO Estimation", "Purchase order estimate tracking by week", "Sales / delivery bridge"),
    ("Resource Allocation", "Who is assigned where across projects", "Resource managers"),
    ("Project Completion", "Completion metrics and status progression", "Portfolio managers"),
]
